version: "3"
services:
  mongodb:
    image: "bitnami/mongodb:latest"
    restart: unless-stopped
    env_file: .env
    environment:
      MONGODB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGODB_DATABASE: ${DATABASE_NAME}
      MONGODB_USERNAME: ${DATABASE_USERNAME}
      MONGODB_PASSWORD: ${DATABASE_PASSWORD}
      MONGODB_DEFAULT_PORT_NUMBER: ${MONGODB_DEFAULT_PORT_NUMBER}
    volumes:
      - "mongodb_data:/bitnami/mongodb"
      # - "./db/mongo:/docker-entrypoint-initdb.d"
    networks:
      - udNodeJs-2
    ports:
      - "${MONGODB_DEFAULT_PORT_NUMBER}:${MONGODB_DEFAULT_PORT_NUMBER}"

volumes:
  mongodb_data:
    driver: local

networks:
  udNodeJs-2:
    name: udNodeJs-2
    driver: bridge
